<?php
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\track_changes\Entity\Change;
use Drupal\block\Entity\Block;
use \Drupal\Core\Link;

/**
 * hook on login to see if the changelog has 
 * been updated since the last login
 */
function track_changes_user_login($account) {
    //check if there were changes since the last time the user logged in
    $lastLoginTime = $account->getLastLoginTime();
    $lastChangeTime = filemtime( $_SERVER['DOCUMENT_ROOT'] . '/changelog.md'); 
    if ( $lastChangeTime <= $lastLoginTime ) {
        $change = Change::create();
        $change->uid->value = $account->id();
        $change->was_seen->value = false;
        $change->save();
    }
}
